# Generated by Django 4.1.7 on 2023-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blogdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('etc1', models.CharField(max_length=100)),
                ('etc2', models.IntegerField(max_length=100)),
                ('etc3', models.FloatField(max_length=1000)),
                ('etc4', models.CharField(max_length=100)),
                ('etc5', models.IntegerField(max_length=100)),
                ('etc6', models.FloatField(max_length=1000)),
                ('etc7', models.CharField(max_length=100)),
                ('etc8', models.IntegerField(max_length=100)),
                ('etc9', models.FloatField(max_length=1000)),
            ],
        ),
    ]
