# Generated by Django 4.1.7 on 2023-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_picture_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_db',
            name='etc4',
        ),
        migrations.RemoveField(
            model_name='picture_db',
            name='etc5',
        ),
        migrations.RemoveField(
            model_name='picture_db',
            name='etc6',
        ),
        migrations.RemoveField(
            model_name='picture_db',
            name='etc7',
        ),
        migrations.RemoveField(
            model_name='picture_db',
            name='etc8',
        ),
        migrations.RemoveField(
            model_name='picture_db',
            name='etc9',
        ),
        migrations.AlterField(
            model_name='picture_db',
            name='etc2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture_db',
            name='etc3',
            field=models.CharField(max_length=100),
        ),
    ]
